Customize thread name prefixes for subscription specific TaskSchedulers
GoogleCloudPlatform/spring-cloud-gcp pull request #1152
Opened 2022-05-30 21:05 UTC by poznachowski

Currently thread names for subscription specific Task Schedulers are lengthy as they comprise of 
`gcp-pubsub-subscriber-` + fully qualified subscription name, ex:
`gcp-pubsub-subscriber-projects/fake project/subscriptions/subscription-name1`

This may result in a lengthy log statement, if thread name is a part of it.

This MR allows customization of subscription specific Task Scheduler's thread names.

2022-06-01 14:23 UTC, elefeint requested changes
It's a nice improvement, but unfortunately accepting a bean in `GcpPubSubAutoConfiguration` constructor that is defined in the same autoconfiguration class leads to  a circular reference. You can test this by starting up the [sample app](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v3.3.0/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/main/java/com/example/PubSubApplication.java). 

I see two ways around this:
1) creating `defaultSelectiveSchedulerThreadNameProvider` in a new autoconfiguration class, 
2) not providing a default bean at all and instead accepting `Optional<SelectiveSchedulerThreadNameProvider> selectiveSchedulerThreadNameProvider` in the constructor.  Then in `registerSelectiveSchedulerBeans`, the default would end up hardcoded as before:
```
        String threadName = selectiveSchedulerThreadNameProvider.isPresent() ? 
            selectiveSchedulerThreadNameProvider.get().getThreadName(fullSubscriptionName) : 
            "gcp-pubsub-subscriber-" + qualifiedName;
```

The second way seems simpler to me, but it's your call.

Also, could you turn on [google style](https://github.com/google/styleguide) and reformat? `mvn validate` will run style checks to make sure it's good.

2022-06-03 17:55 UTC, elefeint requested changes
Looks great!
Would you mind adding a line or two to the _Subscription-specific Configurations_ section in the [reference documentation](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/asciidoc/pubsub.adoc)?

2022-06-04 12:14 UTC, poznachowski commented
Sure, reference added. Please check if that concludes the change.

2022-06-06 14:44 UTC, merged

2022-08-26 11:37 UTC, poznachowski commented
Hey @elefeint ! I don't know where to ask this question elsewhere - Do you have any ETA for publishing new version of spring-cloud-gcp ?

2022-08-29 13:23 UTC, elefeint commented
We'll release in the next 2 weeks. Need to get Spring Boot 2.7 compatibility in.