fix(tests): Re-enable Metrics integration test by renaming
GoogleCloudPlatform/spring-cloud-gcp pull request #118
Opened 2020-11-11 21:02 UTC by ttomsu

Looks like metrics wasn't working this whole time because this test never got picked up. Whoops...

2020-11-11 21:47 UTC, elefeint approved these changes

2020-11-11 21:50 UTC, dzou approved these changes

2020-11-11 21:51 UTC, meltsufin submitted a review, later dismissed
I thought we were using the `*IntegrationTests` pattern for integration tests. Do we just need to list `metrics` as part of the matrix?

2020-11-11 22:18 UTC, ttomsu commented
We are - which is why this test results wasn't firing. I was getting a permission denied error in the old repo w GHA and investigated why I wasn't getting it in the new repo. 

The 'metrics' module is already included in the big list of parallelized integration tests.

2020-11-12 15:01 UTC, elefeint requested changes

2020-11-12 15:18 UTC, ttomsu commented on docs/src/main/asciidoc/migration-guide-1.x.adoc
> +If you're importing the `spring-cloud-gcp-starter-metrics` module, the Stackdriver metrics now need to be explicitly enabled with the property `management.metrics.export.stackdriver.enabled=true`
I think this property is checked for in Spring Boot, so I don't think we can enable it for the user. Source: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/stackdriver/StackdriverMetricsExportAutoConfiguration.java#L50

2020-11-12 19:27 UTC, meltsufin commented on docs/src/main/asciidoc/migration-guide-1.x.adoc
> +If you're importing the `spring-cloud-gcp-starter-metrics` module, the Stackdriver metrics now need to be explicitly enabled with the property `management.metrics.export.stackdriver.enabled=true`
The fault should be enabled, but it looks like something is setting `management.metrics.export.defaults.enabled=false`. Looking more into it.

2020-11-12 20:06 UTC, meltsufin commented on docs/src/main/asciidoc/migration-guide-1.x.adoc
> +If you're importing the `spring-cloud-gcp-starter-metrics` module, the Stackdriver metrics now need to be explicitly enabled with the property `management.metrics.export.stackdriver.enabled=true`
It's done here: https://github.com/spring-projects/spring-boot/commit/b1830da0da05c43e67ffc46e5375261e8eb7859a#diff-196296cded479f093a123da98914f159381d3eef89c33f20148075a58085b34fR53

Basically, Spring Boot Test automatically disabled metrics export, unless you add the `@AutoConfigureMetrics` annotation.

I'll update this branch with that.

2020-11-12 20:38 UTC, elefeint commented on docs/src/main/asciidoc/migration-guide-1.x.adoc
> +If you're importing the `spring-cloud-gcp-starter-metrics` module, the Stackdriver metrics now need to be explicitly enabled with the property `management.metrics.export.stackdriver.enabled=true`
It's ignored in tests, so we need to move the property from `main/resources` to `test/resources`, and no need to document for end users.

2020-11-13 00:32 UTC, ttomsu commented
Tests are back to green now.

2020-11-13 01:51 UTC, meltsufin commented on spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample/pom.xml
> +            <artifactId>spring-boot-starter-actuator</artifactId>
@ttomsu When running from IntelliJ, removing it didn't break the sample for me, but now I see that it's actually required. In fact, I think it needs to be moved int our `spring-cloud-gcp-starter-metrics`.

2020-11-13 03:24 UTC, meltsufin commented
I moved all changes unrelated to re-enabling the test to a separate PR. See: #121

2020-11-16 13:50 UTC, merged