codegen: starter script to generate one module
GoogleCloudPlatform/spring-cloud-gcp pull request #1307
Opened 2022-10-24 22:19 UTC by zhumin8

A naive starter script to start working on the code generation.

run with `./generate-one.sh -c vision -v 3.1.2 -i google-cloud-vision -g com.google.cloud` and this script will generate `/vision` folder with spring code with pom.xml.

2022-10-25 16:41 UTC, elefeint approved these changes

2022-10-25 18:56 UTC, zhumin8 commented
force-pushed after rebase to main.

2022-10-26 14:58 UTC, elefeint requested changes
The `generated/pom.xml` needs to have a packaging specified -- otherwise when building with Maven, you get:
`'packaging' with value 'jar' is invalid. Aggregator projects require 'pom' as packaging.`.

2022-10-26 19:52 UTC, emmileaf commented on generator/generate-one.sh
> +# very not stable change - todo: change to search and replace.
To future-proof for the time being, maybe we can check out googleapis on a specific branch or commit in case this file gets updated?

2022-10-31 23:50 UTC, elefeint requested changes
The starters' pom files either need to have a parent or need to set the target Java version. Right now, you get this when building, say, `com-google-cloud-vision-v1-spring-starter`: 

```
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
```

2022-11-03 12:53 UTC, elefeint approved these changes

2022-11-03 14:01 UTC, merged