Firestore - remove dead code
GoogleCloudPlatform/spring-cloud-gcp pull request #137
Opened 2020-11-21 00:16 UTC by dmitry-s

fixes #136

2020-11-21 00:54 UTC, elefeint requested changes

2020-11-21 00:54 UTC, elefeint commented on spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java
> +		verify(this.firestoreStub, times(1)).commit(any(), any());
Is the second verify redundant?

2020-11-21 00:54 UTC, elefeint commented on spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/FirestoreTemplateTests.java
> +		}).when(this.firestoreStub).commit(any(), any());
This wants to be a helper method.

2020-11-21 00:55 UTC, elefeint commented
I've met this code. Code's, indeed, dead.

2020-11-21 00:56 UTC, elefeint commented
Bigquery integration likely flake, config tests could go either way, but I am puzzled about kotlin tests. I never saw them fail before.

2020-11-23 12:51 UTC, ttomsu commented
Config tests look to be a compile issue - does it work locally for you?

I'm seeing more of these dependency downloads failing. I've heard Maven central is pretty notorious for this kind of flakiness - JCenter allegedly has better reliability, but also is "less secure" because it allows authors to change the packages after publishing. I'm not sure why our GCS mirror isn't being chosen - I'll look into this.

2020-11-23 16:30 UTC, meltsufin approved these changes
LGTM modulo @elefeint's comments.

2020-11-23 21:31 UTC, dmitry-s commented
@ttomsu yes it compiles locally.

2020-11-23 22:57 UTC, elefeint approved these changes

2020-11-24 00:20 UTC, merged