Fixes docs related to keeping a background user thread - pub/sub
GoogleCloudPlatform/spring-cloud-gcp pull request #1404
Opened 2022-12-21 06:36 UTC by bijukunjummen

Fixes docs related to keeping a background user thread for command-line applications. This is based on the discussions in #1182

2022-12-21 19:38 UTC, zhumin8 commented
Do you mind also adding this fix to [`docs/src/main/md/pubsub.md`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/md/pubsub.md)?
We are keeping 2 set of docs in parallel temporarily. Sorry about the inconvenience.

2022-12-21 19:39 UTC, bijukunjummen commented
Will do @zhumin8 , I was wondering about that md file

2022-12-29 16:03 UTC, zhumin8 commented
@mpeddada1 This change LGTM but seems like a temporary workaround. I feel it's worth merging in if we are not actively working on this, WDYT?

2022-12-29 17:27 UTC, mpeddada1 requested changes
@zhumin Agreed. This a helpful workaround to document.

2022-12-29 17:27 UTC, mpeddada1 commented on docs/src/main/asciidoc/pubsub.adoc
> +For a command-line application, a way to keep the application running is to have a user thread(non-daemon thread) started up. A dummy scheduled task creates a threadpool with non-daemon threads:
A minor nit:
How about we rephrase this word to the following?

```suggestion
For a command-line application, a way to keep the application running is to have a user thread(non-daemon thread) started up. A fake scheduled task creates a threadpool with non-daemon threads:
```

2022-12-29 17:27 UTC, mpeddada1 commented on docs/src/main/asciidoc/pubsub.adoc
> +public void dummyScheduledTask() {
```suggestion
public void fakeScheduledTask() {
```

2022-12-29 17:27 UTC, mpeddada1 commented on docs/src/main/md/pubsub.md
> +For a command-line application, a way to keep the application running is to have a user thread(non-daemon thread) started up. A dummy scheduled task creates a threadpool with non-daemon threads:
```suggestion
For a command-line application, a way to keep the application running is to have a user thread(non-daemon thread) started up. A fake scheduled task creates a threadpool with non-daemon threads:
```

2022-12-29 17:27 UTC, mpeddada1 commented on docs/src/main/md/pubsub.md
> +public void dummyScheduledTask() {
```suggestion
public void fakeScheduledTask() {
```

2022-12-29 18:26 UTC, mpeddada1 approved these changes
Thank you @bijukunjummen! LGTM. Will also let @zhumin8 take one final look before merging.

2022-12-29 20:00 UTC, zhumin8 approved these changes

2022-12-29 22:08 UTC, merged