Changes conditional for Spanner and Datastore Transaction Manager
GoogleCloudPlatform/spring-cloud-gcp pull request #1412
Opened 2022-12-24 23:19 UTC by bijukunjummen

Conditional for Spanner is based on missing beans of type SpannerTransactionManager instead of PlatformTransactionManager, this way it always gets created if Spanner libs are pulled in 

Conditional for Datastore is based on missing beans of type DatastoreTransactionManager instead of PlatformTransactionManager, this way it gets created if Datastore libs are pulled in.

It is the user's responsibility to designate the transaction's right transaction manager:

```
@Transactional(transactionManager = "spannerTransactionManager")
```

```
@Transactional(transactionManager = "datastoreTransactionManager")
```

2023-05-01 21:59 UTC, zhumin8 requested changes
Thanks for fixing this and sorry for letting this hang for so long!
 
Just one minor request: Do you mind also adding a note to the documentation that user needs to designate the transaction's right transaction manager if multiple transaction managers are brought in?
The corresponding sections in spanner documentation are [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3.x/docs/src/main/asciidoc/spanner.adoc?plain=1#L951) and [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3.x/docs/src/main/md/spanner.md?plain=1#L1111), datastore documentation are [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3.x/docs/src/main/asciidoc/datastore.adoc?plain=1#L849) and [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3.x/docs/src/main/md/datastore.md?plain=1#L933). (We are keeping adoc and md copies of documentations temporarily)

2023-05-01 22:00 UTC, zhumin8 commented
On a separate note, I've verified this solution manually as we do not have a test setup with both Datastore and Spanner. @JoeWang1127 @meltsufin For future, what do you think about setting up an integration test with multiple data modules we support so we can capture bugs like this one? Or alternatively, there is an existing [sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/3.x/spring-cloud-gcp-samples/spring-cloud-gcp-data-multi-sample) that we could add a test to.

2023-05-02 01:25 UTC, meltsufin commented
I think that re-using the existing sample that already combines Spanner and Datastore makes sense.

Just to clarify, this change doesn't require you to specify `transactionManager` with the `@Transactional`, if only one of the staters is used?

2023-05-02 13:48 UTC, zhumin8 commented
> Just to clarify, this change doesn't require you to specify `transactionManager` with the `@Transactional`, if only one of the staters is used?

Yes, no change of behavior when only one started used. This is the case with existing IT tests with `@Transactional` in [Spanner](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/it/SpannerTemplateIntegrationTests.java#L209) and [Datastore](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-data-datastore/src/test/java/com/google/cloud/spring/data/datastore/it/TransactionalTemplateService.java#L34) and they both work as intended. (Integration tests are skipped for this PR because it's from a forked repo, but I've verified this behavior running from my machine)

2023-05-03 03:50 UTC, bijukunjummen commented
> Thanks for fixing this and sorry for letting this hang for so long!
> 
> Just one minor request: Do you mind also adding a note to the documentation that user needs to designate the transaction's right transaction manager if multiple transaction managers are brought in? The corresponding sections in spanner documentation are [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3.x/docs/src/main/asciidoc/spanner.adoc?plain=1#L951) and [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3.x/docs/src/main/md/spanner.md?plain=1#L1111), datastore documentation are [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3.x/docs/src/main/asciidoc/datastore.adoc?plain=1#L849) and [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3.x/docs/src/main/md/datastore.md?plain=1#L933). (We are keeping adoc and md copies of documentations temporarily)

Done @zhumin8. Thanks for pointing out the exact location for the documentation. Let me know if you want any of the text changed.

2023-05-03 12:38 UTC, JoeWang1127 commented
Hi @bijukunjummen, could you add a test in this [sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/3.x/spring-cloud-gcp-samples/spring-cloud-gcp-data-multi-sample) to verify it's working when connecting Spanner and Datastore?

2023-05-09 02:41 UTC, bijukunjummen commented
> Hi @bijukunjummen, could you add a test in this [sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/3.x/spring-cloud-gcp-samples/spring-cloud-gcp-data-multi-sample) to verify it's working when connecting Spanner and Datastore?

Done @JoeWang1127

2023-05-09 13:35 UTC, JoeWang1127 commented
@bijukunjummen do you think we should change/add the integration tests in samples to verify the samples are working as expected?

2023-05-09 20:16 UTC, zhumin8 requested changes
Sample looks great! Simple and minimum additions. 
Since you are at it, do you mind also adding a test similar to [this existing one](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-multi-sample/src/test/java/com/example/MultipleDataModuleIntegrationTest.java)? It should basically do the same thing as your test, but the test runs in our CI so we are sure this functionality does not accidentally break in the future. 
It could also be useful to mention this change in the sample readme, along the lines of “This sample also demonstrates usage of transactions with both modules.”

2023-05-10 13:52 UTC, meltsufin commented on docs/src/main/asciidoc/datastore.adoc
> +Other Google Cloud database related libraries like spanner, firestore can introduce `PlatformTransactionManager` beans, and can interfere with Datastore Transaction Manager. To disambiguate, explicit
Just a wording suggestion. Please update the other instances as well if you like the rewording.

```suggestion
Other Google Cloud database-related integrations like Spanner and Firestore can introduce `PlatformTransactionManager` beans, and can interfere with the Datastore Transaction Manager. To disambiguate, explicitly specify the name of the transaction manager bean for such `@Transactional` methods. Example:
```

2023-05-13 01:24 UTC, zhumin8 approved these changes
LGTM.
I realized since integration test are not run for this pr, it's fair that adding sample test should not be part of it. I'll add it in a followup pr once this is in.

If you could address the comment on documentation wording, I am good to merge this in.

2023-05-20 00:12 UTC, merged