Splitting the spanner sample into two, one for spanner-template and o…
GoogleCloudPlatform/spring-cloud-gcp pull request #636
Opened 2021-09-30 16:52 UTC by ddixit14

…ne for spanner-repository

2021-10-04 16:16 UTC, elefeint requested changes
Much easier to read than the original squished together sample!

I've left feedback -- ping me with any questions.

2021-10-04 16:16 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/pom.xml
> +    <name>Spring Cloud GCP Code Sample - Spanner</name>
Could you update the module name to specify that it's the repository variant?

2021-10-04 16:16 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/TradeRepository.java
> +public interface TradeRepository extends SpannerRepository<com.example.Trade, Key> {
Try removing the fully qualified path "com.example" everywhere in this class. I think this got added while IntelliJ was still confused about where the entity moved to.

2021-10-04 16:16 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/Trader.java
> +	public void setTrades(List<com.example.Trade> trades) {
Same thing in this class -- the `Trade` class is in the same package, so qualifying the class name with package name should not be necessary.

2021-10-04 16:16 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/TraderRepository.java
> +public interface TraderRepository extends SpannerRepository<com.example.Trader, String> {
... and here.

2021-10-04 16:16 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample/pom.xml
> +    <name>Spring Cloud GCP Code Sample - Spanner</name>
Could you update the module name to specify that it's the template variant?

2021-10-04 16:16 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/pom.xml
> -	<groupId>com.google.cloud</groupId>
Wait, how did Pub/Sub get tangled into this? You will want to revert this file from the pull request. Easiest way is to do "git > compare with branch > main", and accept changes from main.

2021-10-05 22:48 UTC, zhumin8 reviewed
This looks great to me other than minor checkstyle issues. 
I do have one comment below, it can also apply to the template sample module.

2021-10-05 22:48 UTC, zhumin8 commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/SpannerRepositoryExampleDriver.java
Just a thought, what about simplifying this and combine `SpannerRepositoryExampleDriver.java` and  `SpannerRepositoryExample.java`?
 Like in datastore samples: [DatastoreRepositoryExample.java ](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/ad8cac040f8d8853996215c5a7a7ed022d5ced82/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/DatastoreRepositoryExample.java#L53-L52)

2021-10-06 17:50 UTC, mpeddada1 commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample/src/main/java/com/example/SpannerTemplateExampleDriver.java
> +		System.out.println(Arrays.toString(args));
Perhaps we could remove this print statement.

2021-10-06 17:50 UTC, mpeddada1 commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/main/java/com/example/SpannerRepositoryExampleDriver.java
> -			if (!args.containsOption("spanner_repository") && !args.containsOption("spanner_template")) {
Great change! It is much nicer to not have this extra logic anymore.

2021-10-11 18:46 UTC, ddixit14 commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/README.adoc
Yeah that would make things more clear. Will do that.

2021-10-11 20:37 UTC, zhumin8 commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample/src/main/java/com/example/Trade.java
> +@Table(name = "trades")
yep. that's exactly what I had in mind.

2021-10-13 14:17 UTC, elefeint commented on docs/src/main/asciidoc/spanner.adoc
> +Both the samples are listed below :
```suggestion
There are two sample applications available:
```

2021-10-13 14:17 UTC, elefeint commented on docs/src/main/asciidoc/spanner.adoc
> +1. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample[ Sample application for Spanner Template]
```suggestion
1. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample[ Sample application using Spanner Template directly]
```

2021-10-13 14:19 UTC, elefeint commented on docs/src/main/asciidoc/spanner.adoc
> +2. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample[ Sample application for Spanner Repository]
```suggestion
2. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample[ Sample application using higher-level Spanner Repository capabilities]
```

2021-10-13 14:19 UTC, elefeint commented on docs/src/main/asciidoc/spanner.adoc
> +2. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample[ Sample application for Spanner Repository]
This is to make it clear when a user should be looking at one sample vs the other sample.

2021-10-13 14:26 UTC, elefeint commented on spring-cloud-gcp-samples/pom.xml
> -		<module>spring-cloud-gcp-data-spanner-sample</module>
@ddixit14 I think there is a mention left in getting-started.adoc and in spring-cloud-gcp-data-multi-sample.

2021-10-13 14:27 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/README.adoc
> += Spring Cloud GCP Cloud Spanner Starter Example using "Repository"
```suggestion
= Spring Cloud GCP Cloud Spanner Starter Example using Spring Data repositories
```

2021-10-13 14:29 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/README.adoc
> +This code sample demonstrates how to read and write POJOs from Google Cloud Spanner using the Spring Data Cloud Spanner module link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spann
You can say something like "using Spring Data repositories" and link to Spring Data documentation for concepts overview: https://docs.spring.io/spring-data/data-commons/docs/2.5.x/reference/html/#repositories.core-concepts

2021-10-13 14:30 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/README.adoc
> +Run the `SpannerRepositoryExample`  Spring Boot console apps.
```suggestion
Run the `SpannerRepositoryExample`  Spring Boot console app.
```

2021-10-13 14:31 UTC, elefeint commented on spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/README.adoc
>  .. To run the SpannerRepositoryExample:
We don't need this line anymore, since the description above it ("Run the ... console app") only applies to one example now.

2021-10-15 18:00 UTC, merged