WIP: Add SpannerHealthIndicator and AutoConfiguration
GoogleCloudPlatform/spring-cloud-gcp pull request #643
Opened 2021-10-05 16:58 UTC by ikeyat

Fixes #640

**Don't merge. Work in progress:**
 - Test classes are not implemented
 - The documentation is not updated

2021-10-09 07:02 UTC, ikeyat commented
Fix and add tests. Please review.

2021-10-18 16:03 UTC, mpeddada1 commented
Hey @ikeyat, we still need a few more days to review your PR. Thank you for your patience! We appreciate your contribution.

2021-10-31 22:31 UTC, elefeint requested changes
Thank you, and sorry for the delay. 
Please add `@since 2.0.6` tags to new classes, and there is one more inline comment. Otherwise looks very good.

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		SpannerHealthIndicator SpannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```suggestion
		SpannerHealthIndicator spannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		SpannerHealthIndicator.doHealthCheck(builder);
```suggestion
		spannerHealthIndicator.doHealthCheck(builder);
```

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		SpannerHealthIndicator SpannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```suggestion
		spannerHealthIndicator SpannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		SpannerHealthIndicator.doHealthCheck(builder);
```suggestion
		spannerHealthIndicator.doHealthCheck(builder);
```

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		SpannerHealthIndicator SpannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```suggestion
		spannerHealthIndicator SpannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		SpannerHealthIndicator SpannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```suggestion
		SpannerHealthIndicator spannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		assertThat(SpannerHealthIndicator.health().getStatus()).isEqualTo(Status.DOWN);
```suggestion
		assertThat(spannerHealthIndicator.health().getStatus()).isEqualTo(Status.DOWN);
```

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		SpannerHealthIndicator SpannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```suggestion
		SpannerHealthIndicator spannerHealthIndicator = new SpannerHealthIndicator(spannerTemplate, QUERY);
```

2021-10-31 22:31 UTC, elefeint commented on spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicatorTests.java
> +		assertThat(SpannerHealthIndicator.health().getStatus()).isEqualTo(Status.DOWN);
```suggestion
		assertThat(spannerHealthIndicator.health().getStatus()).isEqualTo(Status.DOWN);
```

2021-11-01 16:34 UTC, ikeyat commented
@elefeint 
Thanks for your review. I fixed them.

2021-11-05 20:51 UTC, elefeint approved these changes
This looks great, thank you! Could you add documentation to `spanner.adoc`? Especially around turning the indicator off.

2021-11-08 16:22 UTC, ikeyat commented
@elefeint 
I've updated the adoc!

2021-11-09 20:41 UTC, merged

2021-11-09 20:41 UTC, elefeint commented
@ikeyat Thank you!