Register subscriber flowControlSettings as beans
GoogleCloudPlatform/spring-cloud-gcp pull request #690
Opened 2021-11-10 19:34 UTC by mpeddada1

Part #1 of #671 

This PR registers global and subscription-specific flow control settings as beans in `GcpPubSubAutoConfiguration`. However, note that if a custom bean is provided then the global and subscription-specific beans won't be created.

2021-11-11 15:48 UTC, elefeint requested changes
Looks good. 
Could you also add a test in autoconfiguration to make sure that if no user-provided settings exist (neither either global or subscription specific) that Retry settings default to client library's `Subscriber.getDefaultFlowControlSettings()`? I manually verified that, but we should have a test. We had caused a production issue last summer where we were not falling back correctly to client library values.

2021-11-11 15:49 UTC, elefeint commented
You'd have to actually `createSubscriber()` to validate this, since the logic is in client library building the stub, and not in this project.

2021-11-12 15:47 UTC, mpeddada1 commented
> Could you also add a test in autoconfiguration to make sure that if no user-provided settings exist (neither either global or subscription specific) that Retry settings default to client library's `Subscriber.getDefaultFlowControlSettings()`?

Yes, that is a good idea!

2021-11-12 17:55 UTC, elefeint approved these changes
Thank you!

2021-11-12 19:38 UTC, merged