Add documentation for R2DBC and simplify samples
GoogleCloudPlatform/spring-cloud-gcp pull request #908
Opened 2022-01-25 21:56 UTC by mpeddada1

This PR also modifies the samples to use `R2dbcEntityTemplate` to query databases instead of using `ConnectionFactory` directly. 

Fixes #904

2022-02-01 14:16 UTC, elefeint requested changes
The samples are much nicer with Spring Data!

2022-02-01 14:16 UTC, elefeint commented on docs/src/main/asciidoc/sql.adoc
> +https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-connect-to-production-database[Spring Boot data source auto-configuration] to configure a `Connecti
The link does not point to a specific feature. Might be worth skipping this sentence, since you already explain `ConnectionFactory` above.

2022-02-01 14:16 UTC, elefeint commented on docs/src/main/asciidoc/sql.adoc
> +In other words, properties like the SQL username, `spring.r2dbc.username`, and password, `spring.r2dbc.password` can be used.
```suggestion
Standard R2DBC properties like the SQL username, `spring.r2dbc.username`, and password, `spring.r2dbc.password` can be used.
```

2022-02-01 14:16 UTC, elefeint commented on docs/src/main/asciidoc/sql.adoc
> +Spring Boot starter for Google Cloud SQL registers a `R2dbcCloudSqlEnvironmentPostProcessor` that provides a correctly formatted `spring.r2dbc.url` property to the environment based on the properties
```suggestion
Spring Cloud GCP starter for Google Cloud SQL registers a `R2dbcCloudSqlEnvironmentPostProcessor` that provides a correctly formatted `spring.r2dbc.url` property to the environment based on the properties mentioned above.
```

2022-02-01 14:16 UTC, elefeint commented on docs/src/main/asciidoc/sql.adoc
> +The user properties and the properties provided by the `R2dbcCloudSqlEnvironmentPostProcessor` are then used by https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html[S
They must have rearranged the docs recently because this page stubbornly does not lead to a useful section.

2022-02-01 14:16 UTC, elefeint commented on docs/src/main/asciidoc/sql.adoc
> +Similar to the JDBC support, you can connect to your database with as little as a database and instance names.
I'd move this sentence to the top, so it's the second sentence right after "The Spring Boot Starters for Google Cloud SQL provide an auto-configured https://docs.oracle.com/javaee/7/api/javax/jms/ConnectionFactory.html[`ConnectionFactory`] bean."

This describes the value of the starter.

2022-02-01 14:16 UTC, elefeint commented on docs/src/main/asciidoc/sql.adoc
> +Using the created `ConnectionFactory` in conjunction with Spring R2DBC provides you with a fully configured and operational `R2dbcEntityTemplate` object that you can use to interact with your SQL dat
```suggestion
The customized `ConnectionFactory` is then ready to connect to Cloud SQL. The rest of Spring Data R2DBC objects built on it ( `R2dbcEntityTemplate`,  `DatabaseClient`) are automatically configured and operational, ready to interact with your SQL database.
```

2022-02-03 21:37 UTC, mpeddada1 commented on docs/src/main/asciidoc/sql.adoc
> +The Spring Boot Starters for Google Cloud SQL provide an auto-configured https://docs.oracle.com/javaee/7/api/javax/jms/ConnectionFactory.html[`ConnectionFactory`] bean.
Yes, that is a valid point. We should avoid using Spring Boot starter in that case. Thank you for the suggestions!

2022-02-03 22:28 UTC, mpeddada1 commented on docs/src/main/asciidoc/sql.adoc
> +dependencies {
Good idea, done.

2022-02-03 22:28 UTC, mpeddada1 commented on docs/src/main/asciidoc/sql.adoc
> +You must access the "Google Cloud SQL API" one and enable the API from there.
Done. I removed the sentence that says "pick the first option" and mentioned Cloud SQL instead.

2022-02-04 14:18 UTC, elefeint approved these changes

2022-02-04 14:18 UTC, elefeint commented
The flakes are because this branch does not have the milestone/snapshot removal. I'll rerun them.

2022-02-07 15:35 UTC, merged